id = "2"
question = "Ought every one to believe there is a God?"

[[sections]]
text = "Everyone ought to believe there is a God; and it is their great sin and folly who do not."
verses = "Hebrews 11:6; Psalms 14:1"
