id = "2"
question = "Πρέπει ο καθένας να πιστεύει ότι υπάρχει Θεός;"

[[sections]]
text = "Ο καθένας πρέπει να πιστεύει ότι υπάρχει Θεός· και είναι μεγάλη αμαρτία και ανοησία εκείνων που δεν πιστεύουν."
verses = "Hebrews 11:6; Psalms 14:1"
