id = "3"
question = "Πώς μπορούμε να γνωρίζουμε ότι υπάρχει Θεός;"

[[sections]]
text = "Το φυσικό φως στον άνθρωπο και τα έργα του Θεού δηλώνουν καθαρά ότι υπάρχει Θεός· αλλά μόνο ο λόγος Του και το Πνεύμα Του το πραγματοποιούν πλήρως και αποτελεσματικά προς σωτηρία των αμαρτωλών."
verses = "Romans 1:19,20; Psalms 19:1, 2, 3; Acts 17:24; 1 Corinthians 2:10; 2 Timothy 3:15,16"
