id = "3"
question = "How may we know there is a God?"

[[sections]]
text = "The light of nature in man and the works of God plainly declare there is a God; but his word and Spirit only do it fully and effectually for the salvation of sinners."
verses = "Romans 1:19,20; Psalms 19:1, 2, 3; Acts 17:24; 1 Corinthians 2:10; 2 Timothy 3:15,16"
