id = "4"
question = "Τι είναι ο λόγος του Θεού;"

[[sections]]
text = "Οι Άγιες Γραφές της Παλαιάς και της Καινής Διαθήκης είναι ο λόγος του Θεού και ο μόνος βέβαιος κανόνας πίστεως και υπακοής."
verses = "2 Timothy 3:16; Ephesians 2:20"
