id = "5"
question = "May all men make use of the holy scriptures?"

[[sections]]
text = "All men are not only permitted, but commanded and exhorted to read, hear, and understand the holy scriptures."
verses = "John 5:38; John 17:17,18; Revelation1:3; Acts 8:30"
