id = "5"
question = "Επιτρέπεται σε όλους τους ανθρώπους να κάνουν χρήση των Αγίων Γραφών;"

[[sections]]
text = "Όλοι οι άνθρωποι όχι μόνο επιτρέπεται, αλλά και προστάζονται και προτρέπονται να διαβάζουν, να ακούν και να κατανοούν τις Άγιες Γραφές."
verses = "John 5:38; John 17:17,18; Revelation1:3; Acts 8:30"
