id = "6"
question = "Ποια πράγματα περιέχονται κυρίως στις Άγιες Γραφές;"

[[sections]]
text = "Οι Άγιες Γραφές περιέχουν κυρίως αυτά που ο άνθρωπος οφείλει να πιστεύει σχετικά με τον Θεό, και ποιο καθήκον ο Θεός απαιτεί από τον άνθρωπο."
verses = "2 Timothy 1:13; 3:15,16"
