id = "6"
question = "What things are chiefly contained in the holy scriptures?"

[[sections]]
text = "The holy scriptures chiefly contain what man ought to believe concerning God, and what duty God requires of man."
verses = "2 Timothy 1:13; 3:15,16"
