id = "7"
question = "What is God?"

[[sections]]
text = "God is a Spirit, infinite, eternal, and unchangeable in his being, wisdom, power, holiness, justice, goodness, and truth."
verses = "John 4:24; Job 11:7, 8, 9; Psalms 110:2; James 1:17; Exodus 3:14; Psalms 147:5; Revelation 4:8; Revelation 15:4; Exodus 34:6"
