id = "7"
question = "Τι είναι ο Θεός;"

[[sections]]
text = "Ο Θεός είναι Πνεύμα, άπειρος, αιώνιος και αναλλοίωτος στην ύπαρξή του, τη σοφία, τη δύναμη, την αγιότητα, τη δικαιοσύνη, την αγαθότητα και την αλήθειά του."
verses = "John 4:24; Job 11:7, 8, 9; Psalms 110:2; James 1:17; Exodus 3:14; Psalms 147:5; Revelation 4:8; Revelation 15:4; Exodus 34:6"
