id = "9"
question = "Πόσα πρόσωπα υπάρχουν στη Θεότητα;"

[[sections]]
text = "Υπάρχουν τρία πρόσωπα στη Θεότητα: ο Πατέρας, ο Υιός και το Άγιο Πνεύμα· και αυτά τα τρία είναι ένας Θεός, ίδια στην ουσία, ίσα σε δύναμη και δόξα."
verses = "1 John 5:7; Matthew 28:19"
