id = "9"
question = "How many persons are there in the Godhead?"

[[sections]]
text = "There are three persons in the Godhead, the Father, the Son, and the Holy Spirit; and these three are one God, the same in essence, equal in power and glory."
verses = "1 John 5:7; Matthew 28:19"
