id = "10"
question = "Ποια είναι τα προαιώνια βουλεύματα του Θεού;"

[[sections]]
text = "Τα προαιώνια βουλεύματα του Θεού είναι ο αιώνιος σκοπός του, σύμφωνα με τη βουλή του θελήματός του, διά του οποίου, προς δόξαν του, προόρισε ό,τι συμβαίνει."
verses = "Ephesians 1:4, 11; Romans 9:22-23; Isaiah 46:10; Lamentations 3:37"
