id = "10"
question = "What are the decrees of God?"

[[sections]]
text = "The decrees of God are his eternal purpose according to the counsel of his will, by which, for his own glory, he has foreordained whatsoever comes to pass."
verses = "Ephesians 1:4, 11; Romans 9:22-23; Isaiah 46:10; Lamentations 3:37"
