id = "12"
question = "Τι είναι το έργο της δημιουργίας;"

[[sections]]
text = "Το έργο της δημιουργίας είναι ότι ο Θεός δημιούργησε τα πάντα από το μηδέν, με τον λόγο της δύναμής του, μέσα σε έξι ημέρες, και όλα ήταν πολύ καλά."
verses = "Genesis 1; Hebrews 11:3"
