id = "13"
question = "Πώς δημιούργησε ο Θεός τον άνθρωπο;"

[[sections]]
text = "Ο Θεός δημιούργησε τον άνθρωπο, άνδρα και γυναίκα, σύμφωνα με τη δική του εικόνα, σε γνώση, δικαιοσύνη και αγιότητα, με κυριαρχία πάνω στα δημιουργήματα."
verses = "Genesis 1:26, 27, 28; Colossians 3:10, Ephesians 4:24"
