id = "13"
question = "How did God create man?"

[[sections]]
text = "God created man, male and female, after his own image, in knowledge, righteousness, and holiness, with dominion over the creatures."
verses = "Genesis 1:26, 27, 28; Colossians 3:10, Ephesians 4:24"
