id = "14"
question = "Ποια είναι τα έργα της πρόνοιας του Θεού;"

[[sections]]
text = "Τα έργα της πρόνοιας του Θεού είναι η πανάγια, σοφή και παντοδύναμη διατήρηση και κυβέρνηση όλων των δημιουργημάτων του και όλων των πράξεών τους."
verses = "Psalms 145:17; Isaiah 28:29, Psalms 104:24; Hebrews 1:3; Psalms 103:19; Matthew 10:29, 30, 31"
