id = "15"
question = "Ποια ειδική πράξη πρόνοιας άσκησε ο Θεός προς τον άνθρωπο στην κατάσταση στην οποία δημιουργήθηκε;"

[[sections]]
text = "Όταν ο Θεός δημιούργησε τον άνθρωπο, έκανε μαζί του διαθήκη ζωής με τον όρο της τέλειας υπακοής, και του απαγόρευσε να φάει από το δέντρο της γνώσης του καλού και του κακού, με ποινή τον θάνατο."
verses = "Galatians 3:12; Genesis 2:17"
