id = "16"
question = "Did our first parents continue in the estate in which they were created?"

[[sections]]
text = "Our first parents being left to the freedom of their own will, fell from the estate in which they were created, by sinning against God."
verses = "Genesis 3:6, 7, 8, 13; Ecclesiastes 7:29"
