

id = "16"
question = "Παρέμειναν οι πρώτοι γενάρχες μας στην κατάσταση στην οποία δημιουργήθηκαν;"

[[sections]]
text = "Οι πρώτοι γενάρχες μας, επειδή αφέθηκαν στην ελευθερία της δικής τους βούλησης, εξέπεσαν από την κατάσταση στην οποία δημιουργήθηκαν, και αμάρτησαν ενάντια στον Θεό."
verses = "Genesis 3:6, 7, 8, 13; Ecclesiastes 7:29"
