id = "18"
question = "Ποια ήταν η αμαρτία με την οποία οι πρωτόπλαστοι έπεσαν από την κατάσταση στην οποία δημιουργήθηκαν;"

[[sections]]
text = "Η αμαρτία με την οποία οι πρωτόπλαστοι έπεσαν από την κατάσταση στην οποία δημιουργήθηκαν, ήταν ότι έφαγαν τον απαγορευμένο καρπό."
verses = "Genesis 3:6, 12, 16, 17"
