id = "18"
question = "What was the sin by which our first parents fell from the estate in which they were created?"

[[sections]]
text = "The sin by which our first parents fell from the estate in which they were created, was their eating the forbidden fruit."
verses = "Genesis 3:6, 12, 16, 17"
