id = "19"
question = "Έπεσε όλη η ανθρωπότητα με την πρώτη παράβαση του Αδάμ;"

[[sections]]
text = "Επειδή η διαθήκη έγινε με τον Αδάμ όχι μόνο για τον εαυτό του αλλά και για τους απογόνους του, όλη η ανθρωπότητα που κατάγεται από αυτόν με φυσική γέννηση αμάρτησε μέσα σ' αυτόν και έπεσε μαζί του στην πρώτη του παράβαση."
verses = "Genesis 2:16, 17; Romans 5:12; 1 Corinthians 15:21, 22"
