id = "21"
question = "Wherein consists the sinfulness of that estate into which man fell?"

[[sections]]
text = "The sinfulness of that estate into which man fell, consists in the guilt of Adam's first sin, the want of original righteousness, and the corruption of his whole nature, which is commonly called original sin; together with all actual transgressions which proceed from it."
verses = "Romans 5:12; Ephesians 2:1, 2, 3; James 1:14, 15; Matthew 15:19"
