id = "21"
question = "Σε τι συνίσταται η αμαρτωλότητα της κατάστασης στην οποία έπεσε ο άνθρωπος;"

[[sections]]
text = "Η αμαρτωλότητα της κατάστασης στην οποία έπεσε ο άνθρωπος συνίσταται στην ενοχή της πρώτης αμαρτίας του Αδάμ, στην έλλειψη της αρχικής δικαιοσύνης και στη διαφθορά ολόκληρης της φύσης του, που συνήθως ονομάζεται προπατορικό αμάρτημα· μαζί με όλες τις πραγματικές παραβάσεις που προέρχονται από αυτό."
verses = "Romans 5:12; Ephesians 2:1, 2, 3; James 1:14, 15; Matthew 15:19"
