id = "22"
question = "What is the misery of that estate into which man fell?"

[[sections]]
text = "All mankind by their fall lost communion with God, are under his wrath and curse, and so made liable to all miseries in this life, to death itself, and to the pains of hell for ever."
verses = "Genesis 3:8, 10, 24; Ephesians 2:2, 3; Galatians 3:10; Lamentations 3:39; Romans 6:23; Matthew 25:41, 46"
