id = "22"
question = "Ποια είναι η δυστυχία της κατάστασης στην οποία έπεσε ο άνθρωπος;"

[[sections]]
text = "Ολόκληρο το ανθρώπινο γένος, με την πτώση του, έχασε την κοινωνία με τον Θεό, βρίσκεται κάτω από την οργή και την κατάρα Του, και έτσι είναι υποκείμενο σε όλες τις δυστυχίες αυτής της ζωής, στον ίδιο τον θάνατο, και στις τιμωρίες της κόλασης για πάντα."
verses = "Genesis 3:8, 10, 24; Ephesians 2:2, 3; Galatians 3:10; Lamentations 3:39; Romans 6:23; Matthew 25:41, 46"
