id = "23"
question = "Did God leave all mankind to perish in the estate of sin and misery?"

[[sections]]
text = "God having out of his mere good pleasure, from all eternity, elected some to everlasting life, did enter into a covenant of grace, to deliver them out of the estate of sin and misery, and to bring them into an estate of salvation by a Redeemer."
verses = "Ephesians 1:4, 5; Romans 3:20-22; Galatians 3:21, 22"
