id = "23"
question = "Άφησε ο Θεός όλη την ανθρωπότητα να απολεσθεί στην κατάσταση αμαρτίας και δυστυχίας;"

[[sections]]
text = "Ο Θεός, έχοντας από μόνη την αγαθή Του ευδοκία, από πάσης αιωνιότητος, εκλέξει ορισμένους για αιώνια ζωή, εισήλθε σε διαθήκη χάριτος, για να τους ελευθερώσει από την κατάσταση αμαρτίας και δυστυχίας και να τους οδηγήσει σε κατάσταση σωτηρίας μέσω ενός Λυτρωτή."
verses = "Ephesians 1:4, 5; Romans 3:20-22; Galatians 3:21, 22"
