id = "23"
question = "Άφησε ο Θεός όλη την ανθρωπότητα να χαθεί στην κατάσταση αμαρτίας και δυστυχίας;"

[[sections]]
text = "Ο Θεός, από μόνη τη δική Του αγαθή ευδοκία, διάλεξε από την αιωνιότητα ορισμένους για αιώνια ζωή και έκανε μαζί τους διαθήκη χάριτος, για να τους ελευθερώσει από την κατάσταση αμαρτίας και δυστυχίας και να τους οδηγήσει σε κατάσταση σωτηρίας μέσω ενός Λυτρωτή."
verses = "Ephesians 1:4, 5; Romans 3:20-22; Galatians 3:21, 22"
