id = "24"
question = "Who is the Redeemer of God's elect?"

[[sections]]
text = "The only Redeemer of God's elect is the Lord Jesus Christ; who, being the eternal Son of God, became man, and so was and continues to be God and man in two distinct natures, and one person for ever."
verses = "1 Timothy 2:5, 6; John 1:14; Galatians 4:4; Romans 9:5; Luke 1:35; Colossians 2:9; Hebrews 7:24, 25"
