id = "24"
question = "Ποιος είναι ο Λυτρωτής των εκλεκτών του Θεού;"

[[sections]]
text = "Ο μόνος Λυτρωτής των εκλεκτών του Θεού είναι ο Κύριος Ιησούς Χριστός· ο οποίος, όντας ο αιώνιος Υιός του Θεού, έγινε άνθρωπος, και έτσι ήταν και εξακολουθεί να είναι Θεός και άνθρωπος σε δύο διακριτές φύσεις, και ένα πρόσωπο στους αιώνες."
verses = "1 Timothy 2:5, 6; John 1:14; Galatians 4:4; Romans 9:5; Luke 1:35; Colossians 2:9; Hebrews 7:24, 25"
