id = "25"
question = "Πώς ο Χριστός, ενώ είναι ο Υιός του Θεού, έγινε άνθρωπος;"

[[sections]]
text = "Ο Χριστός, ο Υιός του Θεού, έγινε άνθρωπος παίρνοντας αληθινό σώμα και λογική ψυχή· συνελήφθη με τη δύναμη του Αγίου Πνεύματος στη μήτρα της Παρθένου Μαρίας και γεννήθηκε από αυτήν, χωρίς όμως αμαρτία."
verses = "Hebrews 2:14, 17; 10:5; Matthew 26:38; Luke 1:27, 31, 34, 35, 42; Galatians 4:4; Hebrews 4:15; 7:26"
