id = "27"
question = "Πώς εκτελεί ο Χριστός το αξίωμα του προφήτη;"

[[sections]]
text = "Ο Χριστός εκτελεί το αξίωμα του προφήτη αποκαλύπτοντάς μας, μέσω του λόγου και του Πνεύματός του, το θέλημα του Θεού για τη σωτηρία μας."
verses = "John 1:18; 1 Peter1:10,11, 12; John 15:15; 20:31"
