id = "27"
question = "How does Christ execute the office of a prophet?"

[[sections]]
text = "Christ executes the office of prophet in revealing to us, by his word and Spirit, the will of God for our salvation."
verses = "John 1:18; 1 Peter1:10,11, 12; John 15:15; 20:31"
