id = "28"
question = "How does Christ execute the office of a priest?"

[[sections]]
text = "Christ executes the office of priest in his once offering up himself a sacrifice to satisfy divine justice and reconcile us to God, and in making continual intercession for us."
verses = "Hebrews 9:14, 28; Hebrews 2:17; Hebrews7:24, 25"
