id = "28"
question = "Πώς ασκεί ο Χριστός το αξίωμα του ιερέα;"

[[sections]]
text = "Ο Χριστός ασκεί το αξίωμα του ιερέα με το να προσφέρει εφάπαξ τον εαυτό του θυσία για να ικανοποιήσει τη θεία δικαιοσύνη και να μας συμφιλιώσει με τον Θεό, και με το να μεσιτεύει ακατάπαυστα για εμάς."
verses = "Hebrews 9:14, 28; Hebrews 2:17; Hebrews7:24, 25"
