id = "29"
question = "Πώς ασκεί ο Χριστός το αξίωμα του βασιλέα;"

[[sections]]
text = "Ο Χριστός ασκεί το αξίωμα του βασιλέα υποτάσσοντάς μας στον εαυτό του, κυβερνώντας και προστατεύοντάς μας, και συγκρατώντας και κατανικώντας όλους τους εχθρούς του και μας."
verses = "Acts 15:14, 15, 16; Isaiah 33:22; Isaiah 32:1, 2; 1 Corinthians 15:25; Psalms 110"
