id = "29"
question = "Πώς ασκεί ο Χριστός το αξίωμα του βασιλέα;"

[[sections]]
text = "Ο Χριστός ασκεί το αξίωμα του βασιλέα καθώς μας υποτάσσει στον εαυτό του, μας κυβερνά και μας προστατεύει, και συγκρατεί και κατανικά όλους τους εχθρούς, δικούς του και δικούς μας."
verses = "Acts 15:14, 15, 16; Isaiah 33:22; Isaiah 32:1, 2; 1 Corinthians 15:25; Psalms 110"
