id = "29"
question = "How does Christ execute the office of king?"

[[sections]]
text = "Christ executes the office of a king, in subduing us to himself, in ruling, and defending us, and in restraining and conquering all his and our enemies."
verses = "Acts 15:14, 15, 16; Isaiah 33:22; Isaiah 32:1, 2; 1 Corinthians 15:25; Psalms 110"
