id = "30"
question = "Σε τι συνίστατο η ταπείνωση του Χριστού;"

[[sections]]
text = "Η ταπείνωση του Χριστού συνίστατο στο ότι γεννήθηκε, και μάλιστα σε ταπεινή κατάσταση, στο ότι υποτάχθηκε στον νόμο, υπέμεινε τις θλίψεις αυτής της ζωής, την οργή του Θεού και τον καταραμένο θάνατο του σταυρού· στο ότι ετάφη και παρέμεινε υπό την εξουσία του θανάτου για ένα χρονικό διάστημα."
verses = "Luke 2:7; Galatians 4:4; Hebrews 12:2, 3; Isaiah 53:2, 3; Luke 22:44; Matthew 27:46; Philippians 2:8; 1 Corinthians 15:3,4; Acts 2:24, 25, 26, 27, 31; Matthew 12:40"
