id = "30"
question = "Wherein did Christ's humiliation consist?"

[[sections]]
text = "Christ's humiliation consisted in his being born, and that in a low condition, made under the law, undergoing the miseries of this life, the wrath of God, and the cursed death of the cross; in being buried, and continuing under the power of death for a time."
verses = "Luke 2:7; Galatians 4:4; Hebrews 12:2, 3; Isaiah 53:2, 3; Luke 22:44; Matthew 27:46; Philippians 2:8; 1 Corinthians 15:3,4; Acts 2:24, 25, 26, 27, 31; Matthew 12:40"
