id = "31"
question = "Σε τι συνίσταται η ύψωση του Χριστού;"

[[sections]]
text = "Η ύψωση του Χριστού συνίσταται στην ανάστασή του εκ των νεκρών την τρίτη ημέρα, στην ανάληψή του στον ουρανό, στο ότι κάθεται στα δεξιά του Θεού Πατρός, και στην έλευσή του για να κρίνει τον κόσμο κατά την έσχατη ημέρα."
verses = "1 Corinthians 15:4; Mark 16:19; Ephesians 1:20; Acts 1:11; 17:31"
