id = "32"
question = "How are we made partakers of the redemption purchased by Christ?"

[[sections]]
text = "We are made partakers of the redemption purchased by Christ, by the effectual application of it to us by his Holy Spirit."
verses = "John 1:11,12; Titus 3:5,6"
