id = "32"
question = "Πώς γινόμαστε μέτοχοι της λύτρωσης που αποκτήθηκε από τον Χριστό;"

[[sections]]
text = "Γινόμαστε μέτοχοι της λύτρωσης που αποκτήθηκε από τον Χριστό, διά της αποτελεσματικής εφαρμογής της σε εμάς από το Άγιο Πνεύμα Του."
verses = "John 1:11,12; Titus 3:5,6"
