id = "33"
question = "How does the spirit apply to us the redemption purchased by Christ?"

[[sections]]
text = "The Spirit applies to us the redemption purchased by Christ, by working faith in us, and thereby uniting us to Christ, in our effectual calling."
verses = "Ephesians 1:13, 14; John 6:37, 39; Ephesians 2:8; Ephesians 3:17; 1 Corinthians 1:9"
