id = "33"
question = "Πώς εφαρμόζει το Πνεύμα σε εμάς τη λύτρωση που αγόρασε ο Χριστός;"

[[sections]]
text = "Το Πνεύμα εφαρμόζει σε εμάς τη λύτρωση που αγόρασε ο Χριστός, καθώς ενεργεί μέσα μας την πίστη και μας ενώνει με τον Χριστό, μέσω της αποτελεσματικής μας κλήσης."
verses = "Ephesians 1:13, 14; John 6:37, 39; Ephesians 2:8; Ephesians 3:17; 1 Corinthians 1:9"
