id = "33"
question = "Πώς εφαρμόζει το Πνεύμα σε εμάς τη λύτρωση που αγόρασε ο Χριστός;"

[[sections]]
text = "Το Πνεύμα εφαρμόζει σε εμάς τη λύτρωση που αγόρασε ο Χριστός, ενεργώντας μέσα μας την πίστη, και έτσι ενώνοντάς μας με τον Χριστό, στην αποτελεσματική μας κλήση."
verses = "Ephesians 1:13, 14; John 6:37, 39; Ephesians 2:8; Ephesians 3:17; 1 Corinthians 1:9"
