id = "34"
question = "Τι είναι η αποτελεσματική κλήση;"

[[sections]]
text = "Η αποτελεσματική κλήση είναι το έργο του Πνεύματος του Θεού, διά του οποίου, πείθοντάς μας για την αμαρτία και τη δυστυχία μας, φωτίζοντας τον νου μας στη γνώση του Χριστού και ανανεώνοντας τη θέλησή μας, μας πείθει και μας καθιστά ικανούς να αγκαλιάσουμε τον Ιησού Χριστό, ο οποίος μάς προσφέρεται ελεύθερα στο ευαγγέλιο."
verses = "2 Timothy 1:9; 2 Thessalonians 2:13, 14; Acts 2:37; Acts 26:18; Ezekiel 36:26, 27; John 6:44, 45; Philippians 2:13"
