id = "34"
question = "What is effectual calling?"

[[sections]]
text = "Effectual calling is the work of God's Spirit, by which convincing us of our sin and misery, enlightening our minds in the knowledge of Christ, and renewing our wills, he does persuade and enable us to embrace Jesus Christ freely offered to us in the gospel."
verses = "2 Timothy 1:9; 2 Thessalonians 2:13, 14; Acts 2:37; Acts 26:18; Ezekiel 36:26, 27; John 6:44, 45; Philippians 2:13"
