id = "35"
question = "Ποια ευεργετήματα απολαμβάνουν σε αυτήν τη ζωή εκείνοι που καλούνται αποτελεσματικά;"

[[sections]]
text = "Εκείνοι που καλούνται αποτελεσματικά απολαμβάνουν σε αυτήν τη ζωή τη δικαίωση, την υιοθεσία, τον αγιασμό, και τα διάφορα ευεργετήματα που σε αυτήν τη ζωή είτε συνοδεύουν είτε απορρέουν από αυτά."
verses = "Romans 8:30; Ephesians 1:5; 1 Corinthians 1:30"
