id = "35"
question = "Ποια ευεργετήματα απολαμβάνουν σε αυτήν τη ζωή όσοι καλούνται αποτελεσματικά;"

[[sections]]
text = "Όσοι καλούνται αποτελεσματικά απολαμβάνουν σε αυτήν τη ζωή τη δικαίωση, την υιοθεσία, τον αγιασμό, και τα διάφορα ευεργετήματα που τα συνοδεύουν ή απορρέουν από αυτά σε αυτήν τη ζωή."
verses = "Romans 8:30; Ephesians 1:5; 1 Corinthians 1:30"
