id = "35"
question = "What benefits do they that are effectually called partake of in this life?"

[[sections]]
text = "They that are effectually called do in this life partake of justification, adoption, sanctification, and the several benefits which in this life do either accompany or flow from them."
verses = "Romans 8:30; Ephesians 1:5; 1 Corinthians 1:30"
