id = "36"
question = "Τι είναι η δικαίωση;"

[[sections]]
text = "Η δικαίωση είναι πράξη της ελεύθερης χάριτος του Θεού, με την οποία συγχωρεί όλες τις αμαρτίες μας και μας δέχεται ως δικαίους ενώπιόν του, μόνο χάρη στη δικαιοσύνη του Χριστού που μας καταλογίζεται και λαμβάνεται διά μόνης της πίστεως."
verses = "Romans 3:24, 25; 4:6, 7, 8; 2 Corinthians 5:19, 21; Romans 5:17-19; Galatians 2:16; Philippians 3:9"
