id = "36"
question = "What is justification?"

[[sections]]
text = "Justification is an act of God's free grace, in which he pardons all our sins, and accepts us as righteous in his sight, only for the righteousness of Christ imputed to us, and received by faith alone."
verses = "Romans 3:24, 25; 4:6, 7, 8; 2 Corinthians 5:19, 21; Romans 5:17-19; Galatians 2:16; Philippians 3:9"
