id = "37"
question = "What is adoption?"

[[sections]]
text = "Adoption is an act of God's free grace, by which we are received into the number and have a right to all the privileges of the sons of God."
verses = "1 John 3:1; John 1:12; Romans 8:14-17"
