id = "37"
question = "Τι είναι η υιοθεσία;"

[[sections]]
text = "Η υιοθεσία είναι μια πράξη της ελεύθερης χάριτος του Θεού, με την οποία γινόμαστε δεκτοί στον αριθμό των τέκνων του Θεού και αποκτούμε δικαίωμα σε όλα τα προνόμιά τους."
verses = "1 John 3:1; John 1:12; Romans 8:14-17"
