id = "38"
question = "What is sanctification?"

[[sections]]
text = "Sanctification is the work of God's free grace, by which we are renewed in the whole man after the image of God, and are enabled more and more to die unto sin, and live unto righteousness."
verses = "2 Thessalonians 2:13; Ephesians 4:23, 24; Romans 6:4,6; 8:1"
