

id = "38"
question = "Τι είναι ο αγιασμός;"

[[sections]]
text = "Ο αγιασμός είναι το έργο της ελεύθερης χάριτος του Θεού, μέσω του οποίου ανανεωνόμαστε σε ολόκληρο τον άνθρωπο κατά την εικόνα του Θεού, και γινόμαστε ικανοί ολοένα και περισσότερο να νεκρωνόμαστε ως προς την αμαρτία και να ζούμε σύμφωνα με τη δικαιοσύνη."
verses = "2 Thessalonians 2:13; Ephesians 4:23, 24; Romans 6:4,6; 8:1"
