id = "39"
question = "Ποια είναι τα ευεργετήματα που σε αυτήν τη ζωή συνοδεύουν ή απορρέουν από τη δικαίωση, την υιοθεσία και τον αγιασμό;"

[[sections]]
text = "Τα ευεργετήματα που σε αυτήν τη ζωή συνοδεύουν ή απορρέουν από τη δικαίωση, την υιοθεσία και τον αγιασμό, είναι η βεβαιότητα της αγάπης του Θεού, η ειρήνη της συνείδησης, η χαρά στο Άγιο Πνεύμα, η αύξηση της χάρης και η επιμονή σε αυτήν μέχρι τέλους."
verses = "Romans 5:1, 2, 5; Romans 5:5, 17; Proverbs 4:18; 1 John 5:13; 1 Peter 1:5"
