id = "40"
question = "Ποια ευεργετήματα λαμβάνουν οι πιστοί από τον Χριστό κατά τον θάνατό τους;"

[[sections]]
text = "Οι ψυχές των πιστών κατά τον θάνατό τους τελειοποιούνται στην αγιότητα και περνούν αμέσως στη δόξα· και τα σώματά τους, που παραμένουν ενωμένα με τον Χριστό, αναπαύονται στους τάφους τους μέχρι την ανάσταση."
verses = "Hebrews 12:23; 2 Corinthians 5:1, 6, 8; Philippians 1:23; Luke 23:43; 1 Thessalonians 4:14; Isaiah 57:2; Job 19:26, 27"
