id = "40"
question = "What benefits do believers receive from Christ at their death?"

[[sections]]
text = "The souls of believers are at their death made perfect in holiness, and do immediately pass into glory; and their bodies being still united to Christ, do rest in their graves till the resurrection."
verses = "Hebrews 12:23; 2 Corinthians 5:1, 6, 8; Philippians 1:23; Luke 23:43; 1 Thessalonians 4:14; Isaiah 57:2; Job 19:26, 27"
