id = "41"
question = "Ποια ευεργετήματα λαμβάνουν οι πιστοί από τον Χριστό κατά την ανάσταση;"

[[sections]]
text = "Κατά την ανάσταση, οι πιστοί, που θα αναστηθούν με δόξα, θα αναγνωριστούν φανερά και θα αθωωθούν κατά την ημέρα της κρίσεως, και θα γίνουν τελείως μακάριοι, τόσο στην ψυχή όσο και στο σώμα, στην πλήρη απόλαυση του Θεού στους αιώνες των αιώνων."
verses = "1 Corinthians 15:43; Matthew 25:23; Matthew 10:32; 1 John 3:2; 1 Corinthians 13:12; 1 Thessalonians 4:17, 18"
