id = "41"
question = "What benefits do believers receive from Christ at the resurrection?"

[[sections]]
text = "At the resurrection believers, being raised up in glory, shall be openly acknowledged, and acquitted in the day of judgment, and made perfectly blessed, both in soul and body, in the full enjoyment of God to all eternity."
verses = "1 Corinthians 15:43; Matthew 25:23; Matthew 10:32; 1 John 3:2; 1 Corinthians 13:12; 1 Thessalonians 4:17, 18"
