id = "42"
question = "Αλλά τι θα συμβεί στους ασεβείς κατά τον θάνατό τους;"

[[sections]]
text = "Οι ψυχές των ασεβών θα ριχθούν, κατά τον θάνατό τους, στα βάσανα της κολάσεως, και τα σώματά τους θα κείτονται στους τάφους τους, μέχρι την ανάσταση και την κρίση της μεγάλης ημέρας."
verses = "Luke 16:23, 24; Acts 2:24; Jude 5, 7; 1 Peter 3:19; Psalms 49:14"
