id = "42"
question = "Αλλά τι θα συμβεί στους ασεβείς κατά τον θάνατό τους;"

[[sections]]
text = "Οι ψυχές των ασεβών θα ριχτούν, κατά τον θάνατό τους, στα βάσανα της κόλασης, και τα σώματά τους θα κείτονται στον τάφο τους, μέχρι την ανάσταση και την κρίση της μεγάλης ημέρας."
verses = "Luke 16:23, 24; Acts 2:24; Jude 5, 7; 1 Peter 3:19; Psalms 49:14"
