id = "43"
question = "Τι θα συμβεί στους ασεβείς κατά την ημέρα της κρίσεως;"

[[sections]]
text = "Κατά την ημέρα της κρίσεως, τα σώματα των ασεβών, αφού αναστηθούν από τους τάφους τους, θα καταδικαστούν μαζί με τις ψυχές τους σε ανέκφραστα βασανιστήρια με τον διάβολο και τους αγγέλους του στους αιώνες των αιώνων."
verses = "John 5:28, 29; Matthew 25:41, 46; 2 Thessalonians 1:8, 9"
