id = "44"
question = "Ποιο είναι το καθήκον που ο Θεός απαιτεί από τον άνθρωπο;"

[[sections]]
text = "Το καθήκον που ο Θεός απαιτεί από τον άνθρωπο είναι η υπακοή στο θέλημά Του που μας έχει αποκαλύψει."
verses = "Mic 6:8; 1 Samuel 15:22"
