id = "45"
question = "What did God at first reveal to man for the rule of his obedience?"

[[sections]]
text = "The rule which God at first revealed to man for his obedience, was the moral law."
verses = "Romans 2:14, 15; 10:5"
