id = "45"
question = "Τι αποκάλυψε αρχικά ο Θεός στον άνθρωπο ως κανόνα υπακοής του;"

[[sections]]
text = "Ο κανόνας που ο Θεός αποκάλυψε αρχικά στον άνθρωπο για την υπακοή του ήταν ο ηθικός νόμος."
verses = "Romans 2:14, 15; 10:5"
