id = "46"
question = "Where is the moral law summarily comprehended?"

[[sections]]
text = "The moral law is summarily comprehended in the ten commandments."
verses = "Deuteronomy 10:4; Matthew 19:17"
