id = "47"
question = "Ποια είναι η περίληψη των δέκα εντολών;"

[[sections]]
text = "Η περίληψη των δέκα εντολών είναι να αγαπούμε τον Κύριο και Θεό μας με όλη την καρδιά μας, με όλη την ψυχή μας, με όλη τη δύναμή μας και με όλο τον νου μας· και τον πλησίον μας ως τον εαυτό μας."
verses = "Matthew 22:37-40"
