id = "47"
question = "What is the sum of the ten commandments?"

[[sections]]
text = "The sum of the ten commandments is, to love the Lord our God, with all our heart, with all our soul, with all our strength, and with all our mind; and our neighbour as ourselves."
verses = "Matthew 22:37-40"
