id = "48"
question = "Ποιος είναι ο πρόλογος των δέκα εντολών;"

[[sections]]
text = "Ο πρόλογος των δέκα εντολών είναι στα εξής λόγια: Εγώ είμαι Κύριος ο Θεός σου, ο οποίος σε έβγαλα από τη γη της Αιγύπτου, από τον οίκο της δουλείας."
verses = "Exodus 20:2"
