id = "48"
question = "What is the preface to the ten commandments?"

[[sections]]
text = "The preface to the ten commandments is in these words: I am the Lord thy God which have brought thee out of the land of Egypt, out of the house of bondage."
verses = "Exodus 20:2"
