id = "49"
question = "What does the preface to the ten commandments teach us?"

[[sections]]
text = "The preface to the ten commandments teaches us that because God is the Lord, and our God and redeemer, therefore we are bound to keep all his commandments."
verses = "Luke 1:74, 75; 1 Peter 1:15-19"
