id = "49"
question = "Τι μας διδάσκει ο πρόλογος των δέκα εντολών;"

[[sections]]
text = "Ο πρόλογος των δέκα εντολών μας διδάσκει ότι, επειδή ο Θεός είναι ο Κύριος, ο Θεός μας και ο λυτρωτής μας, γι' αυτό είμαστε υποχρεωμένοι να τηρούμε όλες τις εντολές του."
verses = "Luke 1:74, 75; 1 Peter 1:15-19"
