id = "51"
question = "What is required in the first commandment?"

[[sections]]
text = "The first commandment requires us to know and acknowledge God to be the only true God and our God, and to worship and glorify him accordingly."
verses = "1 Chronicles 28:9; Deuteronomy 26:17; Matthew 4:10; Psalms 29:2"
