id = "51"
question = "Τι απαιτεί η πρώτη εντολή;"

[[sections]]
text = "Η πρώτη εντολή απαιτεί από εμάς να γνωρίζουμε και να αναγνωρίζουμε τον Θεό ως τον μόνο αληθινό Θεό και Θεό μας, και να τον λατρεύουμε και να τον δοξάζουμε ανάλογα."
verses = "1 Chronicles 28:9; Deuteronomy 26:17; Matthew 4:10; Psalms 29:2"
