id = "52"
question = "What is forbidden in the first commandment?"

[[sections]]
text = "The first commandment forbids the denying, or not worshipping and glorifying the true God, as God and our God, and the giving of that worship and glory to any other, which is due unto him alone."
verses = "Psalms 14:1; Romans 1:21; Psalms 81:10, 11; Romans 1:25, 26"
