id = "52"
question = "Τι απαγορεύει η πρώτη εντολή;"

[[sections]]
text = "Η πρώτη εντολή απαγορεύει την άρνηση ή τη μη λατρεία και δόξαση του αληθινού Θεού ως Θεού και Θεού μας, και την απόδοση αυτής της λατρείας και δόξας σε οποιονδήποτε άλλον, η οποία ανήκει μόνο σ' αυτόν."
verses = "Psalms 14:1; Romans 1:21; Psalms 81:10, 11; Romans 1:25, 26"
