id = "52"
question = "Τι απαγορεύει η πρώτη εντολή;"

[[sections]]
text = "Η πρώτη εντολή απαγορεύει την άρνηση ή τη μη λατρεία και δοξολογία του αληθινού Θεού ως Θεού και Θεού μας, καθώς και την απόδοση της λατρείας και της δόξας που ανήκει μόνο σ' αυτόν σε οποιονδήποτε άλλον."
verses = "Psalms 14:1; Romans 1:21; Psalms 81:10, 11; Romans 1:25, 26"
