id = "53"
question = "Τί μάς διδάσκουν ιδιαιτέρως οι λέξεις ενώπιόν μου στην πρώτη εντολή;"

[[sections]]
text = "Οι λέξεις ενώπιόν μου στην πρώτη εντολή μάς διδάσκουν ότι ο Θεός, ο οποίος βλέπει τα πάντα, παρατηρεί και δυσαρεστείται σφόδρα με την αμαρτία του να έχει κανείς οποιονδήποτε άλλον θεό."
verses = "Exodus 8:5"
