id = "53"
question = "What are we especially taught by these words before me, in the first commandment?"

[[sections]]
text = "These words before me, in the first commandment teach us, that God, who sees all things, takes notice of and is much displeased with the sin of having any other god."
verses = "Exodus 8:5"
