id = "54"
question = "Ποια είναι η δεύτερη εντολή;"

[[sections]]
text = "Η δεύτερη εντολή είναι: Δεν θα κάνεις για τον εαυτό σου γλυπτό είδωλο ούτε καμία ομοίωση οτιδήποτε βρίσκεται στον ουρανό επάνω, ή στη γη κάτω, ή στα νερά κάτω από τη γη· δεν θα προσκυνήσεις αυτά ούτε θα τα λατρεύσεις· διότι εγώ, Κύριος ο Θεός σου, είμαι Θεός ζηλότυπος, που επισκέπτομαι την ανομία των πατέρων στα παιδιά μέχρι την τρίτη και τέταρτη γενιά εκείνων που με μισούν· και δείχνω έλεος σε χιλιάδες εκείνων που με αγαπούν και τηρούν τις εντολές μου."
verses = "Exodus 20:4, 5, 6"
