id = "55"
question = "What is required in the second commandment?"

[[sections]]
text = "The second commandment requires the receiving, observing, and keeping pure and entire all such religious worship and ordinances, as God has appointed in his word."
verses = "Deuteronomy 32:46; Matthew 23:20; Acts 2:42"
