id = "55"
question = "Τι απαιτεί η δεύτερη εντολή;"

[[sections]]
text = "Η δεύτερη εντολή απαιτεί την αποδοχή, τήρηση και διαφύλαξη αγνής και ακέραιης κάθε θρησκευτικής λατρείας και διατάξεως που ο Θεός έχει ορίσει στον λόγο του."
verses = "Deuteronomy 32:46; Matthew 23:20; Acts 2:42"
