id = "55"
question = "Τι απαιτεί η δεύτερη εντολή;"

[[sections]]
text = "Η δεύτερη εντολή απαιτεί να δεχόμαστε, να τηρούμε και να διαφυλάσσουμε αγνή και ακέραιη κάθε θρησκευτική λατρεία και διάταξη που ο Θεός έχει ορίσει στον λόγο του."
verses = "Deuteronomy 32:46; Matthew 23:20; Acts 2:42"
