id = "56"
question = "Τι απαγορεύει η δεύτερη εντολή;"

[[sections]]
text = "Η δεύτερη εντολή απαγορεύει τη λατρεία του Θεού μέσω εικόνων ή με οποιονδήποτε άλλο τρόπο που δεν έχει οριστεί στον λόγο του."
verses = "Deuteronomy 4:15-19; Exodus 32:5, 8; Deuteronomy 7:31, 32"
