id = "57"
question = "What are the reasons annexed to the second commandment?"

[[sections]]
text = "The reasons annexed to the second commandment are, God's sovereignty over us, his propriety in us, and the zeal he has to his own worship."
verses = "Psalms 45:2, 3, 6; Psalms 45:11; Exodus 34:13, 14"
