id = "57"
question = "Ποιοι είναι οι λόγοι που συνοδεύουν τη δεύτερη εντολή;"

[[sections]]
text = "Οι λόγοι που συνοδεύουν τη δεύτερη εντολή είναι η κυριαρχία του Θεού πάνω μας, το ότι μας ανήκουμε σ' Αυτόν, και ο ζήλος που έχει για τη δική Του λατρεία."
verses = "Psalms 45:2, 3, 6; Psalms 45:11; Exodus 34:13, 14"
