id = "57"
question = "Ποιοι είναι οι λόγοι που προσαρτώνται στη δεύτερη εντολή;"

[[sections]]
text = "Οι λόγοι που προσαρτώνται στη δεύτερη εντολή είναι η κυριαρχία του Θεού επάνω μας, η ιδιοκτησία του σε εμάς και ο ζήλος που έχει για τη δική του λατρεία."
verses = "Psalms 45:2, 3, 6; Psalms 45:11; Exodus 34:13, 14"
