id = "58"
question = "Ποια είναι η τρίτη εντολή;"

[[sections]]
text = "Η τρίτη εντολή είναι: Δεν θα πάρεις το όνομα του Κυρίου του Θεού σου στα μάταια· διότι ο Κύριος δεν θα αθωώσει εκείνον που παίρνει το όνομά του στα μάταια."
verses = "Exodus 20:7"
