id = "58"
question = "Ποια είναι η τρίτη εντολή;"

[[sections]]
text = "Η τρίτη εντολή είναι: Δεν θα λάβεις το όνομα Κυρίου του Θεού σου επί ματαίω· διότι ο Κύριος δεν θα αθωώσει εκείνον που λαμβάνει το όνομά του επί ματαίω."
verses = "Exodus 20:7"
