id = "59"
question = "What is required in the third commandment?"

[[sections]]
text = "The third commandment requires the holy and reverent use of God's names, titles, attributes, ordinances, word and works."
verses = "Matthew 6:9; Deuteronomy 23:58; Psalms 68:4; Revelation 15:3, 4; Malachi 1:11, 14; Psalms 136:1, 2; Job 36:24"
