id = "59"
question = "Τι απαιτεί η τρίτη εντολή;"

[[sections]]
text = "Η τρίτη εντολή απαιτεί την ιερή και ευλαβική χρήση των ονομάτων, των τίτλων, των ιδιοτήτων, των διατάξεων, του λόγου και των έργων του Θεού."
verses = "Matthew 6:9; Deuteronomy 23:58; Psalms 68:4; Revelation 15:3, 4; Malachi 1:11, 14; Psalms 136:1, 2; Job 36:24"
