id = "60"
question = "Τι απαγορεύεται στην τρίτη εντολή;"

[[sections]]
text = "Η τρίτη εντολή απαγορεύει κάθε βεβήλωση και κατάχρηση οποιουδήποτε μέσου με το οποίο ο Θεός κάνει γνωστό τον εαυτό Του."
verses = "Malachi 1:6, 7, 12; 2:2; 3:14"
