id = "61"
question = "What is the reason annexed to the third commandment?"

[[sections]]
text = "The reason annexed to the third commandment is, that however the breakers of this commandment may escape punishment from men, yet the Lord our God will not suffer them to escape his righteous judgment."
verses = "1 Samuel 2:12, 17, 22, 29; 3:13; Deuteronomy 28:58, 59"
