id = "61"
question = "Ποιος είναι ο λόγος που προστίθεται στην τρίτη εντολή;"

[[sections]]
text = "Ο λόγος που προστίθεται στην τρίτη εντολή είναι ότι, όσο κι αν οι παραβάτες αυτής της εντολής μπορεί να αποφύγουν την τιμωρία από τους ανθρώπους, ωστόσο ο Κύριος ο Θεός μας δεν θα τους αφήσει να ξεφύγουν από τη δίκαιη κρίση Του."
verses = "1 Samuel 2:12, 17, 22, 29; 3:13; Deuteronomy 28:58, 59"
