id = "62"
question = "Ποια είναι η τέταρτη εντολή;"

[[sections]]
text = "Η τέταρτη εντολή είναι: Να θυμάσαι την ημέρα του Σαββάτου και να την αγιάζεις· έξι ημέρες θα εργάζεσαι και θα κάνεις όλες τις εργασίες σου· αλλά η έβδομη ημέρα είναι Σάββατο του Κυρίου του Θεού σου· κατά την ημέρα αυτή δεν θα κάνεις καμία εργασία, εσύ, ούτε ο γιος σου, ούτε η κόρη σου, ούτε ο δούλος σου, ούτε η δούλη σου, ούτε τα ζώα σου, ούτε ο ξένος που βρίσκεται μέσα στις πύλες σου· διότι σε έξι ημέρες ο Κύριος δημιούργησε τον ουρανό και τη γη, τη θάλασσα και όλα όσα υπάρχουν σε αυτά, και αναπαύτηκε την έβδομη ημέρα· γι' αυτό ο Κύριος ευλόγησε την ημέρα του Σαββάτου και την αγίασε."
verses = "Exodus 20:8-11"
