id = "63"
question = "Τι απαιτεί η τέταρτη εντολή;"

[[sections]]
text = "Η τέταρτη εντολή απαιτεί να τηρούμε ως αγίους για τον Θεό τους καθορισμένους χρόνους που Εκείνος έχει ορίσει στον λόγο Του, και συγκεκριμένα, μία ολόκληρη ημέρα στις επτά ως αγία ημέρα σαββατισμού αφιερωμένη σ' Αυτόν."
verses = "Exodus 20:8-11; Deuteronomy 5:12-14"
