id = "63"
question = "What is required in the fourth commandment?"

[[sections]]
text = "The fourth commandment requires the keeping holy to God such set times as he has appointed in his word, expressly, one whole day in seven to be a holy sabbath to himself."
verses = "Exodus 20:8-11; Deuteronomy 5:12-14"
