id = "63"
question = "Τι απαιτεί η τέταρτη εντολή;"

[[sections]]
text = "Η τέταρτη εντολή απαιτεί να τηρούμε ως άγιες για τον Θεό τις καθορισμένες ημέρες που Εκείνος έχει ορίσει στον λόγο Του, και συγκεκριμένα, μία ολόκληρη ημέρα στις επτά ως αγία ημέρα ανάπαυσης αφιερωμένη σ' Αυτόν."
verses = "Exodus 20:8-11; Deuteronomy 5:12-14"
