id = "65"
question = "Πώς πρέπει να αγιάζεται το Σάββατο;"

[[sections]]
text = "Το Σάββατο πρέπει να αγιάζεται με ιερή ανάπαυση σε όλη την ημέρα, ακόμη και από εκείνες τις κοσμικές εργασίες και ψυχαγωγίες που είναι επιτρεπτές τις άλλες ημέρες· και με την αφιέρωση όλου του χρόνου στις δημόσιες και ιδιωτικές ασκήσεις της λατρείας του Θεού, εκτός από όσο χρόνο χρειάζεται να αφιερωθεί σε έργα ανάγκης και ελέους."
verses = "Exodus 20:8, 10; Exodus 16:25-28; Nehemiah 13:15-22; Luke 4:16; Acts 20:7; Psalms 92; Isaiah 66:23; Matthew 12:1-13"
