id = "66"
question = "What is forbidden in the fourth commandment?"

[[sections]]
text = "The fourth commandment forbids the omission or careless performance of the duties required, and the profaning the day by idleness, or doing that which is in itself sinful, or by unnecessary thoughts, words, or works, about worldly employments or recreations."
verses = "Ezekiel 22:26; Amos 8:5; Malachi 1:13; Acts 20:7, 9; Ezekiel 23:38; Jeremiah 17:24-27; Isaiah 58:13"
