id = "66"
question = "Τι απαγορεύεται στην τέταρτη εντολή;"

[[sections]]
text = "Η τέταρτη εντολή απαγορεύει την παράλειψη ή την αμελή εκτέλεση των απαιτούμενων καθηκόντων, και τη βεβήλωση της ημέρας με αργία, ή με πράξεις που είναι καθεαυτές αμαρτωλές, ή με περιττές σκέψεις, λόγια ή έργα σχετικά με κοσμικές ασχολίες ή ψυχαγωγίες."
verses = "Ezekiel 22:26; Amos 8:5; Malachi 1:13; Acts 20:7, 9; Ezekiel 23:38; Jeremiah 17:24-27; Isaiah 58:13"
