id = "67"
question = "What are the reasons annexed to the fourth commandment?"

[[sections]]
text = "The reasons annexed to the fourth commandment, are God's allowing us six days of the week for our own lawful employments, his challenging a special propriety in a seventh, his own example, and his blessing the Sabbath day."
verses = "Exodus 20:9; Exodus 20:11"
