id = "67"
question = "Ποιοι είναι οι λόγοι που συνοδεύουν την τέταρτη εντολή;"

[[sections]]
text = "Οι λόγοι που συνοδεύουν την τέταρτη εντολή είναι ότι ο Θεός μάς παραχωρεί έξι ημέρες της εβδομάδας για τις δικές μας νόμιμες ασχολίες, ότι διεκδικεί ιδιαίτερο δικαίωμα στην έβδομη ημέρα, το δικό Του παράδειγμα, και η ευλογία Του στην ημέρα του Σαββάτου."
verses = "Exodus 20:9; Exodus 20:11"
