id = "68"
question = "Ποια είναι η πέμπτη εντολή;"

[[sections]]
text = "Η πέμπτη εντολή είναι: «Τίμα τον πατέρα σου και τη μητέρα σου, για να μακροημερεύσεις στη γη που σου δίνει ο Κύριος ο Θεός σου.»"
verses = "Exodus 20:12"
