id = "69"
question = "Τι απαιτεί η πέμπτη εντολή;"

[[sections]]
text = "Η πέμπτη εντολή απαιτεί να τιμάμε και να εκπληρώνουμε τα καθήκοντα που αναλογούν στον καθένα ανάλογα με τη θέση και τις σχέσεις του, είτε ως ανώτερος, είτε ως κατώτερος, είτε ως ίσος."
verses = "Ephesians 5:21; 1 Peter 2:17; Romans 12:10"
