id = "69"
question = "What is required in the fifth commandment?"

[[sections]]
text = "The fifth commandment requires the preserving the honour and performing the duties belonging to every one in their several places and relations, as superiors, inferiors, or equals."
verses = "Ephesians 5:21; 1 Peter 2:17; Romans 12:10"
