id = "70"
question = "Τι απαγορεύεται στην πέμπτη εντολή;"

[[sections]]
text = "Η πέμπτη εντολή απαγορεύει την αμέλεια ή την πράξη οτιδήποτε είναι ενάντια στην τιμή και το καθήκον που ανήκει στον καθένα στις διάφορες θέσεις και σχέσεις του."
verses = "Matthew 15:4-6; Ezekiel 34:24; Romans 13:8"
