id = "70"
question = "What is forbidden in the fifth commandment?"

[[sections]]
text = "The fifth commandment forbids the neglect of, or doing any thing against the honour and duty which belongs to every one in their several places and relations."
verses = "Matthew 15:4-6; Ezekiel 34:24; Romans 13:8"
