id = "71"
question = "What is the reason annexed to the fifth commandment?"

[[sections]]
text = "The reason annexed to the fifth commandment is a promise of long life and prosperity to all such as keep this commandment."
verses = "Deuteronomy 5:16; Ephesians 6:2, 3"
