id = "71"
question = "Ποιος είναι ο λόγος που συνοδεύει την πέμπτη εντολή;"

[[sections]]
text = "Ο λόγος που συνοδεύει την πέμπτη εντολή είναι μια υπόσχεση μακροζωίας και ευημερίας σε όλους όσοι τηρούν αυτήν την εντολή."
verses = "Deuteronomy 5:16; Ephesians 6:2, 3"
