id = "73"
question = "Τι απαιτεί η έκτη εντολή;"

[[sections]]
text = "Η έκτη εντολή απαιτεί κάθε νόμιμη προσπάθεια για τη διαφύλαξη της δικής μας ζωής και της ζωής των άλλων."
verses = "Ephesians 5:28,29; 1 Kings 18:4"
