id = "73"
question = "What is required in the sixth commandment?"

[[sections]]
text = "The sixth commandment requires all lawful endeavours to preserve our own life and the life of others."
verses = "Ephesians 5:28,29; 1 Kings 18:4"
