id = "74"
question = "Τι απαγορεύεται στην έκτη εντολή;"

[[sections]]
text = "Η έκτη εντολή απαγορεύει απολύτως την αφαίρεση της δικής μας ζωής ή της ζωής του πλησίον μας αδίκως, ή οτιδήποτε οδηγεί σε αυτό."
verses = "Acts 26:28; Genesis 9:9"
