id = "74"
question = "What is forbidden in the sixth commandment?"

[[sections]]
text = "The sixth commandment absolutely forbids the taking away of our own life, or the life of our neighbour unjustly, or whatsoever tends thereunto."
verses = "Acts 26:28; Genesis 9:9"
