id = "76"
question = "What is required in the seventh commandment?"

[[sections]]
text = "The seventh commandment requires the preservation of our own and our neighbour's chastity, in heart, speech, and behavior."
verses = "1 Corinthians 7:2, 3, 5, 34, 36; Colossians 4:6; 1 Peter 3:2"
