id = "76"
question = "Τι απαιτεί η έβδομη εντολή;"

[[sections]]
text = "Η έβδομη εντολή απαιτεί τη διαφύλαξη της αγνότητας τόσο της δικής μας όσο και του πλησίον μας, στην καρδιά, στον λόγο και στη συμπεριφορά."
verses = "1 Corinthians 7:2, 3, 5, 34, 36; Colossians 4:6; 1 Peter 3:2"
