id = "80"
question = "What is forbidden in the eighth commandment?"

[[sections]]
text = "The eighth commandment forbids whatsoever does or may unjustly hinder our own or our neighbour's wealth or outward estate."
verses = "1 Timothy 5:8; Proverbs 28:19; Proverbs 21:17; 23:20, 21; Ephesians 4:28"
