id = "80"
question = "Τι απαγορεύεται στην όγδοη εντολή;"

[[sections]]
text = "Η όγδοη εντολή απαγορεύει οτιδήποτε εμποδίζει ή μπορεί να εμποδίσει αδίκως τον πλούτο ή την υλική κατάσταση τη δική μας ή του πλησίον μας."
verses = "1 Timothy 5:8; Proverbs 28:19; Proverbs 21:17; 23:20, 21; Ephesians 4:28"
