id = "82"
question = "What is required in the ninth commandment?"

[[sections]]
text = "The ninth commandment requires the maintaining and promoting of truth between man and man, and of our own neighbour's good name, especially in witness bearing."
verses = "Zechariah 8:16; John 5:12; Proverbs 14:5, 25"
