id = "82"
question = "Τι απαιτεί η ένατη εντολή;"

[[sections]]
text = "Η ένατη εντολή απαιτεί τη διατήρηση και προαγωγή της αλήθειας μεταξύ των ανθρώπων, καθώς και την προστασία της καλής φήμης του πλησίον μας, ιδιαίτερα κατά την κατάθεση μαρτυρίας."
verses = "Zechariah 8:16; John 5:12; Proverbs 14:5, 25"
