id = "83"
question = "What is forbidden in the ninth commandment?"

[[sections]]
text = "The ninth commandment forbids whatsoever is prejudicial to the truth, or injurious to our own or our neighbour's good name."
verses = "1 Samuel 17:28; Leviticus 19:16; Psalms 15:2, 3"
