id = "83"
question = "Τι απαγορεύεται στην ένατη εντολή;"

[[sections]]
text = "Η ένατη εντολή απαγορεύει ό,τι είναι επιβλαβές για την αλήθεια ή ό,τι βλάπτει την καλή φήμη τη δική μας ή του πλησίον μας."
verses = "1 Samuel 17:28; Leviticus 19:16; Psalms 15:2, 3"
