id = "84"
question = "Ποια είναι η δέκατη εντολή;"

[[sections]]
text = "Η δέκατη εντολή είναι: Δεν θα επιθυμήσεις το σπίτι του πλησίον σου· δεν θα επιθυμήσεις τη γυναίκα του πλησίον σου, ούτε τον δούλο του, ούτε τη δούλη του, ούτε το βόδι του, ούτε το γαϊδούρι του, ούτε οτιδήποτε ανήκει στον πλησίον σου."
verses = "Exodus 20:17"
