id = "84"
question = "Which is the tenth commandment?"

[[sections]]
text = "The tenth commandment is, Thou shalt not covet thy neighbour's house, thou shalt not covet thy neighbour's wife, nor his man servant, nor his maid servant, nor his ox, nor his ass, nor any thing that is thy neighbour's."
verses = "Exodus 20:17"
