id = "85"
question = "Τι απαιτεί η δέκατη εντολή;"

[[sections]]
text = "Η δέκατη εντολή απαιτεί πλήρη ευχαρίστηση με την κατάστασή μας, με σωστή και αγαθή διάθεση απέναντι στον πλησίον μας και σε όλα όσα του ανήκουν."
verses = "Hebrews 13:5; 1 Timothy 6:6; Job 31:29; Romans 7:15; 1 Timothy 1:5; 1 Corinthians 8:4, 7"
