id = "85"
question = "What is required in the tenth commandment?"

[[sections]]
text = "The tenth commandment requires full contentment with our own condition, with a right and charitable frame of spirit toward our neighbour, and all that is his."
verses = "Hebrews 13:5; 1 Timothy 6:6; Job 31:29; Romans 7:15; 1 Timothy 1:5; 1 Corinthians 8:4, 7"
