id = "86"
question = "Τι απαγορεύεται στη δέκατη εντολή;"

[[sections]]
text = "Η δέκατη εντολή απαγορεύει κάθε δυσαρέσκεια με τη δική μας κατάσταση, τον φθόνο ή τη λύπη για το καλό του πλησίον μας, και κάθε άτακτη επιθυμία και κλίση προς οτιδήποτε ανήκει σε αυτόν."
verses = "1 Kings 21:4; Esther 5:13; 1 Corinthians 10:10; Galatians 5:26; James 3:14, 16; Romans 7:7, 8, 13:9; Deuteronomy 5:21"
