id = "87"
question = "Είναι κάποιος άνθρωπος ικανός να τηρήσει τέλεια τις εντολές του Θεού;"

[[sections]]
text = "Κανένας απλός άνθρωπος μετά την πτώση δεν είναι ικανός σε αυτή τη ζωή να τηρήσει τέλεια τις εντολές του Θεού, αλλά τις παραβαίνει καθημερινά με τη σκέψη, τον λόγο και την πράξη."
verses = "Ecclesiastes 7:20; 1 John 1:8, 10; Galatians 5:17; Genesis 4:5; 7:21; Romans 3:9-21; James 3:2-13"
