id = "87"
question = "Is any man able perfectly to keep the commandments of God?"

[[sections]]
text = "No mere man since the fall is able in this life perfectly to keep the commandments of God, but does daily break them in thought, word, or deed."
verses = "Ecclesiastes 7:20; 1 John 1:8, 10; Galatians 5:17; Genesis 4:5; 7:21; Romans 3:9-21; James 3:2-13"
