id = "88"
question = "Are all transgressions of the law equally heinous?"

[[sections]]
text = "Some sins in themselves, and by reason of several aggravations, are more heinous in the sight of God than others."
verses = "Ezekiel 8:6, 13, 15; 1 John 5:16; Psalms 78:17, 32, 56"
