id = "88"
question = "Είναι όλες οι παραβάσεις του νόμου εξίσου σοβαρές;"

[[sections]]
text = "Ορισμένες αμαρτίες, από τη φύση τους και λόγω διαφόρων επιβαρυντικών συνθηκών, είναι πιο σοβαρές ενώπιον του Θεού από άλλες."
verses = "Ezekiel 8:6, 13, 15; 1 John 5:16; Psalms 78:17, 32, 56"
