id = "89"
question = "What does every sin deserve?"

[[sections]]
text = "Every sin deserves God's wrath and curse, both in this life and that which is to come."
verses = "Ephesians 5:6; Galatians 3:10; Lamentations 3:39; Matthew 25:41; Romans 6:23"
