id = "89"
question = "Τι αξίζει κάθε αμαρτία;"

[[sections]]
text = "Κάθε αμαρτία αξίζει την οργή και την κατάρα του Θεού, τόσο σε αυτήν τη ζωή όσο και στη μέλλουσα."
verses = "Ephesians 5:6; Galatians 3:10; Lamentations 3:39; Matthew 25:41; Romans 6:23"
