id = "90"
question = "What does God require of us that we may escape his wrath and curse, due to us for sin?"

[[sections]]
text = "To escape the wrath and curse of God due to us for sin, God requires of us faith in Jesus Christ, repentance unto life, with the diligent use of all the outward means by which Christ communicates to us the benefits of redemption."
verses = "Acts 20:21; Proverbs 2:1-6; 8:33; Isaiah 55:2, 3"
