id = "90"
question = "Τι απαιτεί ο Θεός από εμάς για να αποφύγουμε την οργή και την κατάρα Του, που μας οφείλονται εξαιτίας της αμαρτίας;"

[[sections]]
text = "Για να αποφύγουμε την οργή και την κατάρα του Θεού που μας οφείλονται εξαιτίας της αμαρτίας, ο Θεός απαιτεί από εμάς πίστη στον Ιησού Χριστό, μετάνοια προς ζωή, μαζί με την επιμελή χρήση όλων των εξωτερικών μέσων μέσω των οποίων ο Χριστός μάς μεταδίδει τα αγαθά της λύτρωσης."
verses = "Acts 20:21; Proverbs 2:1-6; 8:33; Isaiah 55:2, 3"
