id = "91"
question = "Τι είναι η πίστη στον Ιησού Χριστό;"

[[sections]]
text = "Η πίστη στον Ιησού Χριστό είναι σωτήρια χάρη, διά της οποίας δεχόμαστε και στηριζόμαστε σε Αυτόν μόνο για σωτηρία, όπως μας προσφέρεται στο ευαγγέλιο."
verses = "Hebrews 10:39; John 1:12; Isaiah 26:3, 4; Philippians 3:9; Galatians 2:16"
