id = "92"
question = "Τι είναι η μετάνοια προς ζωή;"

[[sections]]
text = "Η μετάνοια προς ζωή είναι σωτήρια χάρη, διά της οποίας ο αμαρτωλός, από αληθινή συναίσθηση της αμαρτίας του και κατανόηση του ελέους του Θεού εν Χριστώ, με θλίψη και μίσος για την αμαρτία του, στρέφεται από αυτήν προς τον Θεό, με πλήρη πρόθεση και προσπάθεια για νέα υπακοή."
verses = "Acts 11:28; Acts 2:37, 38; Joel 2:12; Jeremiah 3:22; Jeremiah 31:18, 19; Ezekiel 36:31; 2 Corinthians 7:11; Isaiah 1:16, 17"
