id = "92"
question = "What is repentance unto life?"

[[sections]]
text = "Repentance unto life is a saving grace, by which a sinner, out of a true sense of his sin, and apprehension of the mercy of God in Christ, does, with grief and hatred of his sin, turn from it unto God, with full purpose of and endeavour after new obedience."
verses = "Acts 11:28; Acts 2:37, 38; Joel 2:12; Jeremiah 3:22; Jeremiah 31:18, 19; Ezekiel 36:31; 2 Corinthians 7:11; Isaiah 1:16, 17"
