id = "93"
question = "What are the outward means by which Christ communicates to us the benefits of redemption?"

[[sections]]
text = "The outward and ordinary means by which Christ communicates to us the benefits of redemption are his ordinances, especially the word, baptism, the Lord's supper, and prayer; all which means are made effectual to the elect for salvation."
verses = "Matthew 28:19, 20; Acts 2:42, 46, 47"
