id = "93"
question = "Ποια είναι τα εξωτερικά μέσα με τα οποία ο Χριστός μάς μεταδίδει τα ευεργετήματα της λύτρωσης;"

[[sections]]
text = "Τα εξωτερικά και τακτικά μέσα με τα οποία ο Χριστός μάς μεταδίδει τα ευεργετήματα της λύτρωσης είναι τα διατάγματά του, ιδιαίτερα ο λόγος, το βάπτισμα, το Δείπνο του Κυρίου και η προσευχή· όλα αυτά τα μέσα καθίστανται αποτελεσματικά για τους εκλεκτούς προς σωτηρία."
verses = "Matthew 28:19, 20; Acts 2:42, 46, 47"
