id = "94"
question = "Πώς γίνεται ο λόγος του Θεού αποτελεσματικός για τη σωτηρία;"

[[sections]]
text = "Το Πνεύμα του Θεού κάνει την ανάγνωση, και ιδιαίτερα το κήρυγμα του λόγου, αποτελεσματικό μέσο για την πεποίθηση και την επιστροφή των αμαρτωλών, καθώς και για την οικοδομή τους στον αγιασμό και την παρηγοριά μέσω της πίστης για σωτηρία."
verses = "Nehemiah 8:8; Acts 26:18; Psalms 19:8; Acts 20:32; Romans 1:15, 16; 10:13, 14, 15, 16, 17; 15:4; 1 Corinthians 14:24, 25; 1 Timothy 3:15, 16, 17"
