id = "94"
question = "How is the word made effectual to salvation?"

[[sections]]
text = "The Spirit of God makes the reading, but especially the preaching of the word, an effectual means of convincing and converting sinners, and of building them up in holiness and comfort through faith unto salvation."
verses = "Nehemiah 8:8; Acts 26:18; Psalms 19:8; Acts 20:32; Romans 1:15, 16; 10:13, 14, 15, 16, 17; 15:4; 1 Corinthians 14:24, 25; 1 Timothy 3:15, 16, 17"
