id = "95"
question = "Πώς πρέπει να διαβάζεται και να ακούγεται ο λόγος του Θεού, ώστε να γίνει αποτελεσματικός προς σωτηρία;"

[[sections]]
text = "Για να γίνει ο λόγος του Θεού αποτελεσματικός προς σωτηρία, πρέπει να τον προσέχουμε με επιμέλεια, προετοιμασία και προσευχή· να τον δεχόμαστε με πίστη και αγάπη, να τον φυλάσσουμε στις καρδιές μας και να τον εφαρμόζουμε στη ζωή μας."
verses = "Proverbs 8:34; 1 Peter 2:1, 2; Psalms 119:18; Hebrews 4:2; 2 Thessalonians 2:10; Psalms 119:18; Luke 8:15; James 1:25"
