id = "95"
question = "How is the word to be read and heard, that it may become effectual to salvation?"

[[sections]]
text = "That the word may become effectual to salvation, we must attend thereunto with diligence, preparation, and prayer; receive it with faith and love, lay it up in our hearts, and practise it in our lives."
verses = "Proverbs 8:34; 1 Peter 2:1, 2; Psalms 119:18; Hebrews 4:2; 2 Thessalonians 2:10; Psalms 119:18; Luke 8:15; James 1:25"
