id = "96"
question = "How do baptism and the Lords supper become effectual means of salvation?"

[[sections]]
text = "Baptism and the Lords supper become effectual means of salvation, not for any virtue in them, or in him that does administer them, but only by the blessing of Christ, and the working of the Spirit in those that by faith receive them."
verses = "1 Peter 3:21; Matthew 3:11; 1 Corinthians 3:6, 7; 1 Corinthians 12:3; Matthew 28:19"
