id = "96"
question = "Πώς το βάπτισμα και το Δείπνο του Κυρίου γίνονται αποτελεσματικά μέσα σωτηρίας;"

[[sections]]
text = "Το βάπτισμα και το Δείπνο του Κυρίου γίνονται αποτελεσματικά μέσα σωτηρίας, όχι λόγω κάποιας δύναμης που υπάρχει σε αυτά ή σε εκείνον που τα τελεί, αλλά μόνο διά της ευλογίας του Χριστού και της ενέργειας του Πνεύματος σε εκείνους που τα δέχονται διά πίστεως."
verses = "1 Peter 3:21; Matthew 3:11; 1 Corinthians 3:6, 7; 1 Corinthians 12:3; Matthew 28:19"
