id = "97"
question = "Τι είναι το βάπτισμα;"

[[sections]]
text = "Το βάπτισμα είναι μια διάταξη της Καινής Διαθήκης που θεσπίστηκε από τον Ιησού Χριστό, ώστε να αποτελεί για τον βαπτιζόμενο σημείο της κοινωνίας του με Αυτόν, στον θάνατο, την ταφή και την ανάστασή Του· του ενσωματωθέντος σε Αυτόν· της αφέσεως των αμαρτιών· και της παραδόσεως του εαυτού του στον Θεό διά του Ιησού Χριστού, για να ζει και να πορεύεται σε καινότητα ζωής."
verses = "Romans 6:3, 4, 5; Colossians 2:12; Galatians 3:27; Mark 1:4; Acts 2:38; 22:16; Romans 6:3, 4"
