id = "97"
question = "What is baptism?"

[[sections]]
text = "Baptism is an ordinance of the New Testament instituted by Jesus Christ, to be unto the party baptized a sign of his fellowship with him, in his death, burial, and resurrection; of his being ingrafted into him; of remission of sins; and of his giving up himself unto God through Jesus Christ, to live and walk in newness of life."
verses = "Romans 6:3, 4, 5; Colossians 2:12; Galatians 3:27; Mark 1:4; Acts 2:38; 22:16; Romans 6:3, 4"
