id = "98"
question = "To whom is baptism to be administered?"

[[sections]]
text = "Baptism is to be administered to all those who actually profess repentance towards God, faith in and obedience to our Lord Jesus Christ, and to none other."
verses = "Acts 2:38; Matthew 3:6; Acts 8:12, 36, 37, 38; 10:47, 48"
