id = "98"
question = "Σε ποιους πρέπει να χορηγείται το βάπτισμα;"

[[sections]]
text = "Το βάπτισμα πρέπει να χορηγείται σε όλους εκείνους που ομολογούν πραγματικά μετάνοια προς τον Θεό, πίστη και υπακοή στον Κύριό μας Ιησού Χριστό, και σε κανέναν άλλον."
verses = "Acts 2:38; Matthew 3:6; Acts 8:12, 36, 37, 38; 10:47, 48"
