id = "99"
question = "Πρέπει τα νήπια όσων ομολογούν πίστη να βαπτίζονται;"

[[sections]]
text = "Τα νήπια όσων ομολογούν πίστη δεν πρέπει να βαπτίζονται, διότι δεν υπάρχει ούτε εντολή ούτε παράδειγμα στις Άγιες Γραφές, ούτε βέβαιο συμπέρασμα από αυτές, για να βαπτίζονται τέτοια νήπια."
verses = "Exodus 23:13; Proverbs 30:6; Luke 3:7, 8"
