id = "99"
question = "Are the infants of such as are professing believers to be baptized?"

[[sections]]
text = "The infants of such as are professing believers are not to be baptized, because there is neither command or example in the holy scriptures, or certain consequence from them to baptize such."
verses = "Exodus 23:13; Proverbs 30:6; Luke 3:7, 8"
