id = "100"
question = "How is Baptism rightly administered?"

[[sections]]
text = "Baptism is rightly administered by immersion, or dipping the whole body of the party in water, into the name of the Father, and of the Son, and of the Holy Spirit, according to Christ's institution, and the practice of the apostles, and not by sprinkling or pouring of water, or dipping some part of the body, after the tradition of men."
verses = "Matthew 3:16; John 3:23; 4:1, 2; Matthew 28:19, 20; Acts 8:38; Romans 6:4; Colossians 2:12"
