id = "100"
question = "Πώς τελείται ορθά το Βάπτισμα;"

[[sections]]
text = "Το Βάπτισμα τελείται ορθά διά καταδύσεως, δηλαδή με τη βύθιση ολόκληρου του σώματος του βαπτιζομένου μέσα στο νερό, στο όνομα του Πατρός και του Υιού και του Αγίου Πνεύματος, σύμφωνα με την εντολή του Χριστού και την πρακτική των αποστόλων, και όχι με ραντισμό ή επίχυση νερού, ούτε με βύθιση μέρους μόνο του σώματος, κατά την παράδοση των ανθρώπων."
verses = "Matthew 3:16; John 3:23; 4:1, 2; Matthew 28:19, 20; Acts 8:38; Romans 6:4; Colossians 2:12"
