id = "101"
question = "Ποιο είναι το καθήκον εκείνων που έχουν βαπτιστεί ορθά;"

[[sections]]
text = "Είναι καθήκον εκείνων που έχουν βαπτιστεί ορθά να αφιερώσουν τον εαυτό τους σε μια συγκεκριμένη και ευτάκτως οργανωμένη εκκλησία του Ιησού Χριστού, ώστε να περπατούν σε όλες τις εντολές και τα διατάγματα του Κυρίου άμεμπτα."
verses = "Acts 2:41, 42; 5:13, 14; 9:26; 1 Peter 2:5; Luke 1:6"
