id = "101"
question = "Ποιο είναι το καθήκον όσων έχουν βαπτιστεί σωστά;"

[[sections]]
text = "Είναι καθήκον όσων έχουν βαπτιστεί σωστά να αφιερώσουν τον εαυτό τους σε μια συγκεκριμένη και σωστά οργανωμένη εκκλησία του Ιησού Χριστού, ώστε να ζουν σύμφωνα με όλες τις εντολές και τα διατάγματα του Κυρίου με τρόπο άμεμπτο."
verses = "Acts 2:41, 42; 5:13, 14; 9:26; 1 Peter 2:5; Luke 1:6"
