id = "101"
question = "What is the duty of such who are rightly baptized?"

[[sections]]
text = "It is the duty of such who are rightly baptized to give up themselves to some particular and orderly church of Jesus Christ, that they may walk in all the commandments and ordinances of the Lord blameless."
verses = "Acts 2:41, 42; 5:13, 14; 9:26; 1 Peter 2:5; Luke 1:6"
