id = "102"
question = "Τι είναι το Δείπνο του Κυρίου;"

[[sections]]
text = "Το Δείπνο του Κυρίου είναι μια διάταξη της Καινής Διαθήκης, που θεσπίστηκε από τον Ιησού Χριστό· κατά την οποία, με την προσφορά και λήψη άρτου και οίνου, σύμφωνα με την εντολή του, διακηρύσσεται ο θάνατός του, και οι άξιοι μετέχοντες γίνονται — όχι κατά σωματικό και σαρκικό τρόπο, αλλά διά της πίστεως — κοινωνοί του σώματος και του αίματός του, μαζί με όλες τις ευεργεσίες του, προς πνευματική τους τροφή και αύξηση στη χάρη."
verses = "Matthew 26:26, 27, 28; 1 Corinthians 11:23-26; 10:16"
