id = "102"
question = "What is the Lord's supper?"

[[sections]]
text = "The Lord's supper is an ordinance of the New Testament, instituted by Jesus Christ; in which by giving and receiving bread and wine, according to his appointment, his death is shown forth, and the worthy receivers are, not after a corporal and carnal manner, but by faith, made partakers of his body and blood, with all his benefits, to their spiritual nourishment and growth in grace."
verses = "Matthew 26:26, 27, 28; 1 Corinthians 11:23-26; 10:16"
