id = "103"
question = "Ποια είναι τα κατάλληλα υποκείμενα αυτού του θεσμού;"

[[sections]]
text = "Όσοι έχουν βαπτιστεί κατόπιν προσωπικής ομολογίας της πίστης τους στον Ιησού Χριστό και μετάνοιας από νεκρά έργα."
verses = "Acts 2:41, 42"
