id = "103"
question = "Ποιοι είναι τα κατάλληλα υποκείμενα αυτού του θεσμού;"

[[sections]]
text = "Εκείνοι που έχουν βαπτιστεί κατόπιν προσωπικής ομολογίας της πίστεώς τους στον Ιησού Χριστό και μετανοίας από νεκρά έργα."
verses = "Acts 2:41, 42"
