id = "104"
question = "Τι απαιτείται για την άξια συμμετοχή στο Δείπνο του Κυρίου;"

[[sections]]
text = "Από εκείνους που επιθυμούν να συμμετάσχουν αξίως στο Δείπνο του Κυρίου, απαιτείται να εξετάζουν τους εαυτούς τους ως προς τη γνώση τους για να διακρίνουν το σώμα του Κυρίου, ως προς την πίστη τους για να τρέφονται από αυτόν, ως προς τη μετάνοια, την αγάπη και τη νέα υπακοή τους· ώστε να μη μεταλαμβάνουν ανάξια και να τρώνε και να πίνουν κρίμα στον εαυτό τους."
verses = "1 Corinthians 11:28, 29; 2 Corinthians 13:5; 1 Corinthians 11:31; 1 Corinthians 10:16, 17; 1 Corinthians 5:7, 8; 1 Corinthians 11:28, 29"
