id = "105"
question = "Τι είναι η προσευχή;"

[[sections]]
text = "Η προσευχή είναι η προσφορά των επιθυμιών μας στον Θεό, με τη βοήθεια του Αγίου Πνεύματος, για πράγματα σύμφωνα με το θέλημά του, στο όνομα του Χριστού, με πίστη, με εξομολόγηση των αμαρτιών μας και με ευγνώμονη αναγνώριση των ελεών του."
verses = "Psalms 62:8; Romans 8:26; 1 John 5:14; Romans 8:27; John 16:23; Matthew 21:22; James 1:6; Psalms 32:5, 6; Daniel 9:4; Philippians 4:6"
