id = "105"
question = "What is prayer?"

[[sections]]
text = "Prayer is an offering up our desires to God, by the assistance of the Holy Spirit, for things agreeable to his will, in the name of Christ, believing, with confession of our sins, and thankful acknowledgments of his mercies."
verses = "Psalms 62:8; Romans 8:26; 1 John 5:14; Romans 8:27; John 16:23; Matthew 21:22; James 1:6; Psalms 32:5, 6; Daniel 9:4; Philippians 4:6"
