id = "106"
question = "Ποιον κανόνα έχει δώσει ο Θεός για την καθοδήγησή μας στην προσευχή;"

[[sections]]
text = "Ολόκληρος ο λόγος του Θεού είναι χρήσιμος για να μας καθοδηγεί στην προσευχή· αλλά ο ειδικός κανόνας καθοδήγησης είναι εκείνη η προσευχή που ο Χριστός δίδαξε στους μαθητές του, η οποία συνήθως ονομάζεται Κυριακή Προσευχή."
verses = "1 John 5:14; Matthew 6:9-13; Luke 11:2-4"
