id = "106"
question = "What rule has God given for our direction in prayer?"

[[sections]]
text = "The whole word of God is of use to direct us in prayer; but the special rule of direction is that prayer which Christ taught his disciples, commonly called the Lord's prayer."
verses = "1 John 5:14; Matthew 6:9-13; Luke 11:2-4"
