id = "107"
question = "Τι μας διδάσκει ο πρόλογος της Κυριακής Προσευχής;"

[[sections]]
text = "Ο πρόλογος της Κυριακής Προσευχής, που είναι «Πάτερ ημών ο εν τοις ουρανοίς», μας διδάσκει να προσεγγίζουμε τον Θεό με άγιο σεβασμό και εμπιστοσύνη, όπως τα παιδιά προσεγγίζουν έναν πατέρα που είναι ικανός και πρόθυμος να μας βοηθήσει· και ότι πρέπει να προσευχόμαστε μαζί με άλλους και για χάρη άλλων."
verses = "Matthew 6:9; Romans 8:15; Luke 11:13; Isaiah 24:8; Acts 12:5; 1 Timothy 2:1, 2"
