id = "107"
question = "What does the preface of the Lord's prayer teach us?"

[[sections]]
text = "The preface of the Lord's prayer, which is Our Father which art in heaven, teaches us to draw near to God with all holy reverence and confidence, as children to a father, able and ready to help us; and that we should pray with and for others."
verses = "Matthew 6:9; Romans 8:15; Luke 11:13; Isaiah 24:8; Acts 12:5; 1 Timothy 2:1, 2"
