id = "108"
question = "What do we pray for in the first petition?"

[[sections]]
text = "In the first petition, which is, Hallowed be thy name, we pray that God would enable us and others to glorify him in all that by which he makes himself known, and that he would dispose all things to his own glory."
verses = "Matthew 6:9; Psalms 67:2, 3; Psalms 83; Romans 11:36"
