id = "108"
question = "Τι ζητούμε στο πρώτο αίτημα;"

[[sections]]
text = "Στο πρώτο αίτημα, που είναι «Ἁγιασθήτω τὸ ὄνομά σου», προσευχόμαστε ο Θεός να μας αξιώσει, εμάς και τους άλλους, να τον δοξάζουμε σε όλα εκείνα με τα οποία γνωστοποιεί τον εαυτό του, και να διαθέτει τα πάντα προς δόξαν του."
verses = "Matthew 6:9; Psalms 67:2, 3; Psalms 83; Romans 11:36"
