id = "109"
question = "Τι ζητούμε στο δεύτερο αίτημα;"

[[sections]]
text = "Στο δεύτερο αίτημα, που είναι «Ελθέτω η βασιλεία σου», προσευχόμαστε να καταστραφεί η βασιλεία του Σατανά, να προοδεύσει η βασιλεία της χάριτος, να οδηγηθούμε εμείς και οι άλλοι σ' αυτήν και να διατηρηθούμε σ' αυτήν, και να επισπευσθεί η έλευση της βασιλείας της δόξας."
verses = "Matthew 6:10; Psalms 68:1, 18; Revelation 12:10, 11; 2 Thessalonians 3:1; Romans 10:1; John 17:19, 20; Revelation 22:10"
