id = "109"
question = "What do we pray for in the second petition?"

[[sections]]
text = "In the second petition, which is, Your kingdom come, we pray that Satan's kingdom may be destroyed, and that the kingdom of grace may be advanced, ourselves and others brought into it and kept in it, and that the kingdom of glory may be hastened."
verses = "Matthew 6:10; Psalms 68:1, 18; Revelation 12:10, 11; 2 Thessalonians 3:1; Romans 10:1; John 17:19, 20; Revelation 22:10"
