id = "110"
question = "What do we pray for in the third petition?"

[[sections]]
text = "In the third petition, which is, Your will be done on earth as it is in heaven, we pray that God by his grace would make us able and willing to know, obey, and submit to his will in all things, as the angels do in heaven."
verses = "Matthew 6:10; Psalms 67; Psalms 119:36; 2 Samuel 15:25; Job 1:21; Psalms 103:20, 21"
