

id = "110"
question = "Τι ζητούμε στο τρίτο αίτημα;"

[[sections]]
text = "Στο τρίτο αίτημα, που είναι «Γενηθήτω το θέλημά σου, ως εν ουρανώ, και επί της γης», προσευχόμαστε ο Θεός με τη χάρη του να μας κάνει ικανούς και πρόθυμους να γνωρίζουμε, να υπακούμε και να υποτασσόμαστε στο θέλημά του σε όλα τα πράγματα, όπως κάνουν οι άγγελοι στον ουρανό."
verses = "Matthew 6:10; Psalms 67; Psalms 119:36; 2 Samuel 15:25; Job 1:21; Psalms 103:20, 21"
