id = "111"
question = "Τι ζητούμε στο τέταρτο αίτημα;"

[[sections]]
text = "Στο τέταρτο αίτημα, που είναι «Τον άρτον ημών τον επιούσιον δος ημίν σήμερον», προσευχόμαστε να λάβουμε από τη δωρεάν χάρη του Θεού ένα επαρκές μερίδιο από τα αγαθά αυτής της ζωής και να απολαμβάνουμε την ευλογία Του μαζί με αυτά."
verses = "Matthew 6:11; Proverbs 30:8; Genesis 28:20; 1 Timothy 4:4, 5"
