id = "111"
question = "What do we pray for in the fourth petition?"

[[sections]]
text = "In the fourth petition, which is, Give us this day our daily bread, we pray that of God's free gift we may receive a competent portion of the good things of this life, and enjoy his blessing with them."
verses = "Matthew 6:11; Proverbs 30:8; Genesis 28:20; 1 Timothy 4:4, 5"
