id = "112"
question = "What do we pray for in the fifth petition?"

[[sections]]
text = "In the fifth petition, which is, And forgive us our debts as we forgive our debtors, we pray that God, for Christ's sake, would freely pardon all our sins; which we are rather encouraged to ask because of his grace we are enabled from the heart to forgive others."
verses = "Matthew 6:12; Psalms 51:1, 2, 7, 9; Daniel 9:17-19; Luke 11:4; Matthew 18:35"
