id = "112"
question = "Τι ζητούμε στο πέμπτο αίτημα;"

[[sections]]
text = "Στο πέμπτο αίτημα, το οποίο είναι: Καὶ συγχώρησέ μας τα χρέη μας, όπως κι εμείς συγχωρούμε τους χρεώστες μας, προσευχόμαστε ο Θεός, χάριν του Χριστού, να συγχωρήσει ελεύθερα όλες τις αμαρτίες μας· και μάλιστα ενθαρρυνόμαστε να το ζητήσουμε αυτό, επειδή με τη χάρη του είμαστε ικανοί να συγχωρούμε τους άλλους από καρδιάς."
verses = "Matthew 6:12; Psalms 51:1, 2, 7, 9; Daniel 9:17-19; Luke 11:4; Matthew 18:35"
