id = "113"
question = "Τι ζητούμε στο έκτο αίτημα;"

[[sections]]
text = "Στο έκτο αίτημα, το οποίο είναι: Και μη μας εισφέρεις σε πειρασμό, αλλά ελευθέρωσέ μας από το κακό, προσευχόμαστε ο Θεός είτε να μας φυλάξει από το να πειρασθούμε στην αμαρτία, είτε να μας στηρίξει και να μας ελευθερώσει όταν πειραζόμαστε."
verses = "Matthew 6:13; Matthew 26:31; 2 Corinthians 12:8"
