id = "113"
question = "What do we pray for in the sixth petition?"

[[sections]]
text = "In the sixth petition, which is, And lead us not into temptation but deliver us from evil, we pray that God would either keep us from being tempted to sin, or support and deliver us when we are tempted."
verses = "Matthew 6:13; Matthew 26:31; 2 Corinthians 12:8"
