id = "114"
question = "What does the conclusion of the Lord's prayer teach us?"

[[sections]]
text = "The conclusion of the Lord's prayer, which is, for thine is the kingdom, and the power, and the glory forever, Amen, teaches us to take our encouragement in prayer from God only, and in our prayers to praise him, ascribing kingdom, power and glory to him; and in testimony of our desire and assurance to be heard we say, Amen."
verses = "Matthew 6:13; Daniel 9:4, 7-9, 16-19; 1 Chronicles 29:10-13; 1 Corinthians 4:16; Revelation 22:20, 21"
