id = "114"
question = "Τι μας διδάσκει το συμπέρασμα της Κυριακής Προσευχής;"

[[sections]]
text = "Το συμπέρασμα της Κυριακής Προσευχής, το οποίο είναι «ότι σου είναι η βασιλεία και η δύναμη και η δόξα στους αιώνες, Αμήν», μας διδάσκει να αντλούμε το θάρρος μας στην προσευχή μόνο από τον Θεό, και στις προσευχές μας να Τον δοξάζουμε, αποδίδοντάς Του βασιλεία, δύναμη και δόξα· και ως μαρτυρία της επιθυμίας και της βεβαιότητάς μας ότι θα εισακουστούμε, λέμε Αμήν."
verses = "Matthew 6:13; Daniel 9:4, 7-9, 16-19; 1 Chronicles 29:10-13; 1 Corinthians 4:16; Revelation 22:20, 21"
